<?php

namespace ContainerG4UJRP0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XRy0XVYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XRy0XVY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XRy0XVY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\ArticleController::editArticle' => ['privates', '.service_locator.i9Y0h6B', 'get_ServiceLocator_I9Y0h6BService', true],
            'App\\Controller\\Admin\\CategoryController::editCategory' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\AuthorController::article' => ['privates', '.service_locator.i9Y0h6B', 'get_ServiceLocator_I9Y0h6BService', true],
            'App\\Controller\\AuthorController::author' => ['privates', '.service_locator.Hawz9dz', 'get_ServiceLocator_Hawz9dzService', true],
            'App\\Controller\\AuthorController::showAuthor' => ['privates', '.service_locator.qy9c7FJ', 'get_ServiceLocator_Qy9c7FJService', true],
            'App\\Controller\\BienController::createBien' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\BienController::editBien' => ['privates', '.service_locator.yLCDnwT', 'get_ServiceLocator_YLCDnwTService', true],
            'App\\Controller\\DefaultController::biens' => ['privates', '.service_locator.BgZuR4d', 'get_ServiceLocator_BgZuR4dService', true],
            'App\\Controller\\DefaultController::locataires' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\DefaultController::locations' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\DefaultController::mandataires' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\LocataireController::createUser' => ['privates', '.service_locator.BgZuR4d', 'get_ServiceLocator_BgZuR4dService', true],
            'App\\Controller\\LocataireController::editUser' => ['privates', '.service_locator.pSCcLp9', 'get_ServiceLocator_PSCcLp9Service', true],
            'App\\Controller\\LocationController::createLocation' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\MandataireController::editUser' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Admin\\ArticleController:editArticle' => ['privates', '.service_locator.i9Y0h6B', 'get_ServiceLocator_I9Y0h6BService', true],
            'App\\Controller\\Admin\\CategoryController:editCategory' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\AuthorController:article' => ['privates', '.service_locator.i9Y0h6B', 'get_ServiceLocator_I9Y0h6BService', true],
            'App\\Controller\\AuthorController:author' => ['privates', '.service_locator.Hawz9dz', 'get_ServiceLocator_Hawz9dzService', true],
            'App\\Controller\\AuthorController:showAuthor' => ['privates', '.service_locator.qy9c7FJ', 'get_ServiceLocator_Qy9c7FJService', true],
            'App\\Controller\\BienController:createBien' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\BienController:editBien' => ['privates', '.service_locator.yLCDnwT', 'get_ServiceLocator_YLCDnwTService', true],
            'App\\Controller\\DefaultController:biens' => ['privates', '.service_locator.BgZuR4d', 'get_ServiceLocator_BgZuR4dService', true],
            'App\\Controller\\DefaultController:locataires' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\DefaultController:locations' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\DefaultController:mandataires' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\LocataireController:createUser' => ['privates', '.service_locator.BgZuR4d', 'get_ServiceLocator_BgZuR4dService', true],
            'App\\Controller\\LocataireController:editUser' => ['privates', '.service_locator.pSCcLp9', 'get_ServiceLocator_PSCcLp9Service', true],
            'App\\Controller\\LocationController:createLocation' => ['privates', '.service_locator.Z496Fkm', 'get_ServiceLocator_Z496FkmService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\MandataireController:editUser' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Admin\\ArticleController::editArticle' => '?',
            'App\\Controller\\Admin\\CategoryController::editCategory' => '?',
            'App\\Controller\\AuthorController::article' => '?',
            'App\\Controller\\AuthorController::author' => '?',
            'App\\Controller\\AuthorController::showAuthor' => '?',
            'App\\Controller\\BienController::createBien' => '?',
            'App\\Controller\\BienController::editBien' => '?',
            'App\\Controller\\DefaultController::biens' => '?',
            'App\\Controller\\DefaultController::locataires' => '?',
            'App\\Controller\\DefaultController::locations' => '?',
            'App\\Controller\\DefaultController::mandataires' => '?',
            'App\\Controller\\LocataireController::createUser' => '?',
            'App\\Controller\\LocataireController::editUser' => '?',
            'App\\Controller\\LocationController::createLocation' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\MandataireController::editUser' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\ArticleController:editArticle' => '?',
            'App\\Controller\\Admin\\CategoryController:editCategory' => '?',
            'App\\Controller\\AuthorController:article' => '?',
            'App\\Controller\\AuthorController:author' => '?',
            'App\\Controller\\AuthorController:showAuthor' => '?',
            'App\\Controller\\BienController:createBien' => '?',
            'App\\Controller\\BienController:editBien' => '?',
            'App\\Controller\\DefaultController:biens' => '?',
            'App\\Controller\\DefaultController:locataires' => '?',
            'App\\Controller\\DefaultController:locations' => '?',
            'App\\Controller\\DefaultController:mandataires' => '?',
            'App\\Controller\\LocataireController:createUser' => '?',
            'App\\Controller\\LocataireController:editUser' => '?',
            'App\\Controller\\LocationController:createLocation' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\MandataireController:editUser' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
