<?php

namespace ContainerNvcEmry;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DzE6aTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dzE6a_T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dzE6a_T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'residenceRepository' => ['privates', 'App\\Repository\\ResidenceRepository', 'getResidenceRepositoryService', true],
        ], [
            'residenceRepository' => 'App\\Repository\\ResidenceRepository',
        ]);
    }
}
