<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Residence extends \App\Entity\Residence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'zip_code', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'inventoryFile', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'representative', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'residence'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'zip_code', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'inventoryFile', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'representative', '' . "\0" . 'App\\Entity\\Residence' . "\0" . 'residence'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Residence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $city): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(string $zip_code): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zip_code]);

        return parent::setZipCode($zip_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(string $country): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventoryFile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventoryFile', []);

        return parent::getInventoryFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setInventoryFile(string $inventoryFile): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInventoryFile', [$inventoryFile]);

        return parent::setInventoryFile($inventoryFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(?\App\Entity\User $owner): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentative(): ?\App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentative', []);

        return parent::getRepresentative();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentative(?\App\Entity\Rent $representative): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentative', [$representative]);

        return parent::setRepresentative($representative);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidence(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidence', []);

        return parent::getResidence();
    }

    /**
     * {@inheritDoc}
     */
    public function addResidence(\App\Entity\Rent $residenceId): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addResidence', [$residenceId]);

        return parent::addResidence($residenceId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeResidenceId(\App\Entity\Rent $residence): \App\Entity\Residence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeResidenceId', [$residence]);

        return parent::removeResidenceId($residence);
    }

}
