<?php

namespace ContainerQdcWZxN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_52RmIYsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52RmIYs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52RmIYs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\ArticleController::editArticle' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\CategoryController::editCategory' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\AuthorController::article' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AuthorController::author' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\AuthorController::showAuthor' => ['privates', '.service_locator.BMU75HS', 'get_ServiceLocator_BMU75HSService', true],
            'App\\Controller\\BienController::createBien' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\BienController::editBien' => ['privates', '.service_locator.Cidn584', 'get_ServiceLocator_Cidn584Service', true],
            'App\\Controller\\DefaultController::biens' => ['privates', '.service_locator.dzE6a_T', 'get_ServiceLocator_DzE6aTService', true],
            'App\\Controller\\DefaultController::locataires' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\DefaultController::locations' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\DefaultController::mandataires' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\DefaultController::showLocations' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\LocataireController::createUser' => ['privates', '.service_locator.dzE6a_T', 'get_ServiceLocator_DzE6aTService', true],
            'App\\Controller\\LocataireController::editUser' => ['privates', '.service_locator.IQTlz_A', 'get_ServiceLocator_IQTlzAService', true],
            'App\\Controller\\LocationController::createLocation' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\MandataireController::editUser' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\ArticleController:editArticle' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\Admin\\CategoryController:editCategory' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\AuthorController:article' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\AuthorController:author' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\AuthorController:showAuthor' => ['privates', '.service_locator.BMU75HS', 'get_ServiceLocator_BMU75HSService', true],
            'App\\Controller\\BienController:createBien' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\BienController:editBien' => ['privates', '.service_locator.Cidn584', 'get_ServiceLocator_Cidn584Service', true],
            'App\\Controller\\DefaultController:biens' => ['privates', '.service_locator.dzE6a_T', 'get_ServiceLocator_DzE6aTService', true],
            'App\\Controller\\DefaultController:locataires' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\DefaultController:locations' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\DefaultController:mandataires' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\DefaultController:showLocations' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\LocataireController:createUser' => ['privates', '.service_locator.dzE6a_T', 'get_ServiceLocator_DzE6aTService', true],
            'App\\Controller\\LocataireController:editUser' => ['privates', '.service_locator.IQTlz_A', 'get_ServiceLocator_IQTlzAService', true],
            'App\\Controller\\LocationController:createLocation' => ['privates', '.service_locator.6Le8TYh', 'get_ServiceLocator_6Le8TYhService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\MandataireController:editUser' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\ArticleController::editArticle' => '?',
            'App\\Controller\\Admin\\CategoryController::editCategory' => '?',
            'App\\Controller\\AuthorController::article' => '?',
            'App\\Controller\\AuthorController::author' => '?',
            'App\\Controller\\AuthorController::showAuthor' => '?',
            'App\\Controller\\BienController::createBien' => '?',
            'App\\Controller\\BienController::editBien' => '?',
            'App\\Controller\\DefaultController::biens' => '?',
            'App\\Controller\\DefaultController::locataires' => '?',
            'App\\Controller\\DefaultController::locations' => '?',
            'App\\Controller\\DefaultController::mandataires' => '?',
            'App\\Controller\\DefaultController::showLocations' => '?',
            'App\\Controller\\LocataireController::createUser' => '?',
            'App\\Controller\\LocataireController::editUser' => '?',
            'App\\Controller\\LocationController::createLocation' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\MandataireController::editUser' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\ArticleController:editArticle' => '?',
            'App\\Controller\\Admin\\CategoryController:editCategory' => '?',
            'App\\Controller\\AuthorController:article' => '?',
            'App\\Controller\\AuthorController:author' => '?',
            'App\\Controller\\AuthorController:showAuthor' => '?',
            'App\\Controller\\BienController:createBien' => '?',
            'App\\Controller\\BienController:editBien' => '?',
            'App\\Controller\\DefaultController:biens' => '?',
            'App\\Controller\\DefaultController:locataires' => '?',
            'App\\Controller\\DefaultController:locations' => '?',
            'App\\Controller\\DefaultController:mandataires' => '?',
            'App\\Controller\\DefaultController:showLocations' => '?',
            'App\\Controller\\LocataireController:createUser' => '?',
            'App\\Controller\\LocataireController:editUser' => '?',
            'App\\Controller\\LocationController:createLocation' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\MandataireController:editUser' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
