<?php

namespace ContainerW26Q870;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5HlQWvDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5HlQWvD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5HlQWvD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', '.errored.1lo4kkj', NULL, 'Cannot determine controller argument for "App\\Controller\\LoginController::index()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils".'],
        ], [
            'authenticationUtils' => '?',
        ]);
    }
}
