<?php

namespace ContainerW26Q870;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_1lo4kkjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.1lo4kkj' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LoginController::index()": the $authenticationUtils argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils".');
    }
}
