<?php

namespace ContainerSQx5USq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IQTlzAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IQTlz_A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IQTlz_A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'residenceRepository' => ['privates', 'App\\Repository\\ResidenceRepository', 'getResidenceRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'residenceRepository' => 'App\\Repository\\ResidenceRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
