<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRWU6Ofn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRWU6Ofn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRWU6Ofn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRWU6Ofn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRWU6Ofn\App_KernelDevDebugContainer([
    'container.build_hash' => 'RWU6Ofn',
    'container.build_id' => 'a836a2d7',
    'container.build_time' => 1641055383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRWU6Ofn');
