<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPJ41Ez0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPJ41Ez0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPJ41Ez0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPJ41Ez0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPJ41Ez0\App_KernelDevDebugContainer([
    'container.build_hash' => 'PJ41Ez0',
    'container.build_id' => '1579e435',
    'container.build_time' => 1646669268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPJ41Ez0');
