<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9GXl8GK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9GXl8GK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9GXl8GK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9GXl8GK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9GXl8GK\App_KernelDevDebugContainer([
    'container.build_hash' => '9GXl8GK',
    'container.build_id' => '13baf416',
    'container.build_time' => 1649075817,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9GXl8GK');
